"""initial schema

Revision ID: 1178628c8b28
Revises: 
Create Date: 2026-03-19 20:09:34.878119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '1178628c8b28'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_type',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schema_version', sa.String(length=50), server_default='1.0', nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_type')),
    sa.UniqueConstraint('code', name='uq_report_type_code')
    )
    op.create_index('ix_report_type_is_active', 'report_type', ['is_active'], unique=False)
    op.create_table('role',
    sa.Column('code', sa.Enum('admin', 'manager', 'operator', 'viewer', name='role_code_enum'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role')),
    sa.UniqueConstraint('code', name='uq_role_code'),
    sa.UniqueConstraint('name', name='uq_role_name')
    )
    op.create_table('user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=150), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_blocked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_user_role_id_role'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name='uq_user_email')
    )
    op.create_index('ix_user_is_active', 'user', ['is_active'], unique=False)
    op.create_index('ix_user_is_blocked', 'user', ['is_blocked'], unique=False)
    op.create_index('ix_user_role_id', 'user', ['role_id'], unique=False)
    op.create_table('ml_template',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_type', sa.Enum('classification', 'extraction', 'normalization', 'hybrid', name='template_type_enum'), nullable=False),
    sa.Column('target_report_type_id', sa.BigInteger(), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_path', sa.String(length=512), nullable=True),
    sa.Column('version', sa.String(length=50), server_default='1.0', nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_ml_template_created_by_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_report_type_id'], ['report_type.id'], name=op.f('fk_ml_template_target_report_type_id_report_type'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ml_template')),
    sa.UniqueConstraint('code', 'version', name='uq_ml_template_code_version')
    )
    op.create_index('ix_ml_template_created_by', 'ml_template', ['created_by'], unique=False)
    op.create_index('ix_ml_template_is_active', 'ml_template', ['is_active'], unique=False)
    op.create_index('ix_ml_template_is_default', 'ml_template', ['is_default'], unique=False)
    op.create_index('ix_ml_template_target_report_type_id', 'ml_template', ['target_report_type_id'], unique=False)
    op.create_table('project',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_project_owner_id_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project')),
    sa.UniqueConstraint('code', name='uq_project_code'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_project_owner_name')
    )
    op.create_index('ix_project_is_archived', 'project', ['is_archived'], unique=False)
    op.create_index('ix_project_owner_id', 'project', ['owner_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.Enum('create', 'update', 'delete', 'submit', 'approve', 'reject', 'process_start', 'process_retry', 'process_finish', 'login', 'logout', 'export', name='audit_action_enum'), nullable=False),
    sa.Column('entity_type', sa.Enum('user', 'project', 'report', 'report_upload', 'template', 'task', 'dashboard', name='audit_entity_type_enum'), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('before_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_audit_log_project_id_project'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_audit_log_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_action', 'audit_log', ['action'], unique=False)
    op.create_index('ix_audit_log_created_at', 'audit_log', ['created_at'], unique=False)
    op.create_index('ix_audit_log_entity_id', 'audit_log', ['entity_id'], unique=False)
    op.create_index('ix_audit_log_entity_type', 'audit_log', ['entity_type'], unique=False)
    op.create_index('ix_audit_log_project_id', 'audit_log', ['project_id'], unique=False)
    op.create_index('ix_audit_log_user_id', 'audit_log', ['user_id'], unique=False)
    op.create_table('project_member',
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('member_role', sa.Enum('owner', 'manager', 'editor', 'viewer', name='project_member_role_enum'), nullable=False),
    sa.Column('added_by', sa.BigInteger(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['user.id'], name=op.f('fk_project_member_added_by_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_project_member_project_id_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_project_member_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_member')),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_member_project_user')
    )
    op.create_index('ix_project_member_project_id', 'project_member', ['project_id'], unique=False)
    op.create_index('ix_project_member_user_id', 'project_member', ['user_id'], unique=False)
    op.create_table('report',
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('report_type_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('report_period_start', sa.Date(), nullable=False),
    sa.Column('report_period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'on_review', 'on_approval', 'approved', 'rejected', 'rework', 'archived', name='report_status_enum'), server_default='draft', nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('current_assignee_id', sa.BigInteger(), nullable=True),
    sa.Column('approver_id', sa.BigInteger(), nullable=True),
    sa.Column('ml_template_id', sa.BigInteger(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_comment', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint('report_period_end >= report_period_start', name=op.f('ck_report_report_period_range_valid')),
    sa.ForeignKeyConstraint(['approver_id'], ['user.id'], name=op.f('fk_report_approver_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], name=op.f('fk_report_creator_id_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['current_assignee_id'], ['user.id'], name=op.f('fk_report_current_assignee_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ml_template_id'], ['ml_template.id'], name=op.f('fk_report_ml_template_id_ml_template'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_report_project_id_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_type_id'], ['report_type.id'], name=op.f('fk_report_report_type_id_report_type'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report'))
    )
    op.create_index('ix_report_creator_id', 'report', ['creator_id'], unique=False)
    op.create_index('ix_report_ml_template_id', 'report', ['ml_template_id'], unique=False)
    op.create_index('ix_report_project_id', 'report', ['project_id'], unique=False)
    op.create_index('ix_report_report_type_id', 'report', ['report_type_id'], unique=False)
    op.create_index('ix_report_status', 'report', ['status'], unique=False)
    op.create_table('report_upload',
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('report_type_id', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_by', sa.BigInteger(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('is_latest', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('upload_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.CheckConstraint('file_size >= 0', name=op.f('ck_report_upload_report_upload_file_size_non_negative')),
    sa.CheckConstraint('upload_version >= 1', name=op.f('ck_report_upload_report_upload_version_positive')),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_report_upload_project_id_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], name=op.f('fk_report_upload_report_id_report'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_type_id'], ['report_type.id'], name=op.f('fk_report_upload_report_type_id_report_type'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], name=op.f('fk_report_upload_uploaded_by_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_upload')),
    sa.UniqueConstraint('report_id', 'upload_version', name='uq_report_upload_report_version'),
    sa.UniqueConstraint('storage_path', name='uq_report_upload_storage_path')
    )
    op.create_index('ix_report_upload_checksum_sha256', 'report_upload', ['checksum_sha256'], unique=False)
    op.create_index('ix_report_upload_is_latest', 'report_upload', ['is_latest'], unique=False)
    op.create_index('ix_report_upload_project_id', 'report_upload', ['project_id'], unique=False)
    op.create_index('ix_report_upload_report_id', 'report_upload', ['report_id'], unique=False)
    op.create_index('ix_report_upload_report_type_id', 'report_upload', ['report_type_id'], unique=False)
    op.create_index('ix_report_upload_uploaded_by', 'report_upload', ['uploaded_by'], unique=False)
    op.create_table('processing_task',
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('report_upload_id', sa.BigInteger(), nullable=False),
    sa.Column('ml_template_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'success', 'failed', 'retry', 'cancelled', name='processing_status_enum'), server_default='queued', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='5', nullable=False),
    sa.Column('progress', sa.Integer(), server_default='0', nullable=False),
    sa.Column('params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('warning_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(quality_score IS NULL) OR (quality_score >= 0 AND quality_score <= 1)', name=op.f('ck_processing_task_processing_task_quality_score_range')),
    sa.CheckConstraint('error_count >= 0', name=op.f('ck_processing_task_processing_task_error_count_non_negative')),
    sa.CheckConstraint('priority >= 1 AND priority <= 10', name=op.f('ck_processing_task_processing_task_priority_range')),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name=op.f('ck_processing_task_processing_task_progress_range')),
    sa.CheckConstraint('retry_count >= 0', name=op.f('ck_processing_task_processing_task_retry_count_non_negative')),
    sa.CheckConstraint('warning_count >= 0', name=op.f('ck_processing_task_processing_task_warning_count_non_negative')),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_processing_task_created_by_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ml_template_id'], ['ml_template.id'], name=op.f('fk_processing_task_ml_template_id_ml_template'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], name=op.f('fk_processing_task_report_id_report'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_upload_id'], ['report_upload.id'], name=op.f('fk_processing_task_report_upload_id_report_upload'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_task')),
    sa.UniqueConstraint('celery_task_id', name='uq_processing_task_celery_task_id')
    )
    op.create_index('ix_processing_task_created_by', 'processing_task', ['created_by'], unique=False)
    op.create_index('ix_processing_task_ml_template_id', 'processing_task', ['ml_template_id'], unique=False)
    op.create_index('ix_processing_task_queued_at', 'processing_task', ['queued_at'], unique=False)
    op.create_index('ix_processing_task_report_id', 'processing_task', ['report_id'], unique=False)
    op.create_index('ix_processing_task_report_upload_id', 'processing_task', ['report_upload_id'], unique=False)
    op.create_index('ix_processing_task_status', 'processing_task', ['status'], unique=False)
    op.create_table('normalized_dataset',
    sa.Column('processing_task_id', sa.BigInteger(), nullable=False),
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('rows_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('schema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preview_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data_location', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.CheckConstraint('rows_count >= 0', name=op.f('ck_normalized_dataset_normalized_dataset_rows_count_non_negative')),
    sa.ForeignKeyConstraint(['processing_task_id'], ['processing_task.id'], name=op.f('fk_normalized_dataset_processing_task_id_processing_task'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], name=op.f('fk_normalized_dataset_report_id_report'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_normalized_dataset')),
    sa.UniqueConstraint('processing_task_id', name='uq_normalized_dataset_processing_task_id')
    )
    op.create_index('ix_normalized_dataset_created_at', 'normalized_dataset', ['created_at'], unique=False)
    op.create_index('ix_normalized_dataset_report_id', 'normalized_dataset', ['report_id'], unique=False)
    op.create_table('notification',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('report_id', sa.BigInteger(), nullable=True),
    sa.Column('processing_task_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.Enum('report_status_changed', 'report_submitted', 'report_approved', 'report_rejected', 'task_failed', 'task_completed', 'system_alert', name='notification_type_enum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.ForeignKeyConstraint(['processing_task_id'], ['processing_task.id'], name=op.f('fk_notification_processing_task_id_processing_task'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_notification_project_id_project'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], name=op.f('fk_notification_report_id_report'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_notification_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    op.create_index('ix_notification_created_at', 'notification', ['created_at'], unique=False)
    op.create_index('ix_notification_is_read', 'notification', ['is_read'], unique=False)
    op.create_index('ix_notification_processing_task_id', 'notification', ['processing_task_id'], unique=False)
    op.create_index('ix_notification_project_id', 'notification', ['project_id'], unique=False)
    op.create_index('ix_notification_report_id', 'notification', ['report_id'], unique=False)
    op.create_index('ix_notification_type', 'notification', ['type'], unique=False)
    op.create_index('ix_notification_user_id', 'notification', ['user_id'], unique=False)
    op.create_table('processing_log',
    sa.Column('processing_task_id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.Enum('debug', 'info', 'warning', 'error', name='processing_log_level_enum'), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.ForeignKeyConstraint(['processing_task_id'], ['processing_task.id'], name=op.f('fk_processing_log_processing_task_id_processing_task'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_log'))
    )
    op.create_index('ix_processing_log_created_at', 'processing_log', ['created_at'], unique=False)
    op.create_index('ix_processing_log_level', 'processing_log', ['level'], unique=False)
    op.create_index('ix_processing_log_processing_task_id', 'processing_log', ['processing_task_id'], unique=False)
    op.create_index('ix_processing_log_stage', 'processing_log', ['stage'], unique=False)
    op.create_table('task_error',
    sa.Column('processing_task_id', sa.BigInteger(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('field_path', sa.String(length=255), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('source_value', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('is_critical', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.ForeignKeyConstraint(['processing_task_id'], ['processing_task.id'], name=op.f('fk_task_error_processing_task_id_processing_task'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_error'))
    )
    op.create_index('ix_task_error_error_code', 'task_error', ['error_code'], unique=False)
    op.create_index('ix_task_error_error_type', 'task_error', ['error_type'], unique=False)
    op.create_index('ix_task_error_is_critical', 'task_error', ['is_critical'], unique=False)
    op.create_index('ix_task_error_processing_task_id', 'task_error', ['processing_task_id'], unique=False)
    op.create_index('ix_task_error_row_number', 'task_error', ['row_number'], unique=False)
    op.create_table('dashboard',
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('report_id', sa.BigInteger(), nullable=True),
    sa.Column('normalized_dataset_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dashboard_type', sa.Enum('personal', 'department', 'executive', 'system', name='dashboard_type_enum'), nullable=False),
    sa.Column('source_type', sa.Enum('normalized_dataset', 'report', 'project_aggregate', name='dashboard_source_type_enum'), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('filters_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('layout_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_shared', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['normalized_dataset_id'], ['normalized_dataset.id'], name=op.f('fk_dashboard_normalized_dataset_id_normalized_dataset'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_dashboard_owner_id_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_dashboard_project_id_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], name=op.f('fk_dashboard_report_id_report'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboard')),
    sa.UniqueConstraint('owner_id', 'project_id', 'name', name='uq_dashboard_owner_project_name')
    )
    op.create_index('ix_dashboard_dashboard_type', 'dashboard', ['dashboard_type'], unique=False)
    op.create_index('ix_dashboard_normalized_dataset_id', 'dashboard', ['normalized_dataset_id'], unique=False)
    op.create_index('ix_dashboard_owner_id', 'dashboard', ['owner_id'], unique=False)
    op.create_index('ix_dashboard_project_id', 'dashboard', ['project_id'], unique=False)
    op.create_index('ix_dashboard_report_id', 'dashboard', ['report_id'], unique=False)
    op.create_index('ix_dashboard_source_type', 'dashboard', ['source_type'], unique=False)
    op.create_table('export_artifact',
    sa.Column('processing_task_id', sa.BigInteger(), nullable=True),
    sa.Column('report_id', sa.BigInteger(), nullable=True),
    sa.Column('dashboard_id', sa.BigInteger(), nullable=True),
    sa.Column('format', sa.Enum('csv', 'xlsx', 'pdf', name='export_format_enum'), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.CheckConstraint('file_size >= 0', name=op.f('ck_export_artifact_export_artifact_file_size_non_negative')),
    sa.CheckConstraint('processing_task_id IS NOT NULL OR report_id IS NOT NULL OR dashboard_id IS NOT NULL', name=op.f('ck_export_artifact_export_artifact_has_source')),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_export_artifact_created_by_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboard.id'], name=op.f('fk_export_artifact_dashboard_id_dashboard'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['processing_task_id'], ['processing_task.id'], name=op.f('fk_export_artifact_processing_task_id_processing_task'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], name=op.f('fk_export_artifact_report_id_report'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_export_artifact')),
    sa.UniqueConstraint('storage_path', name='uq_export_artifact_storage_path')
    )
    op.create_index('ix_export_artifact_created_by', 'export_artifact', ['created_by'], unique=False)
    op.create_index('ix_export_artifact_dashboard_id', 'export_artifact', ['dashboard_id'], unique=False)
    op.create_index('ix_export_artifact_format', 'export_artifact', ['format'], unique=False)
    op.create_index('ix_export_artifact_processing_task_id', 'export_artifact', ['processing_task_id'], unique=False)
    op.create_index('ix_export_artifact_report_id', 'export_artifact', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_export_artifact_report_id', table_name='export_artifact')
    op.drop_index('ix_export_artifact_processing_task_id', table_name='export_artifact')
    op.drop_index('ix_export_artifact_format', table_name='export_artifact')
    op.drop_index('ix_export_artifact_dashboard_id', table_name='export_artifact')
    op.drop_index('ix_export_artifact_created_by', table_name='export_artifact')
    op.drop_table('export_artifact')
    op.drop_index('ix_dashboard_source_type', table_name='dashboard')
    op.drop_index('ix_dashboard_report_id', table_name='dashboard')
    op.drop_index('ix_dashboard_project_id', table_name='dashboard')
    op.drop_index('ix_dashboard_owner_id', table_name='dashboard')
    op.drop_index('ix_dashboard_normalized_dataset_id', table_name='dashboard')
    op.drop_index('ix_dashboard_dashboard_type', table_name='dashboard')
    op.drop_table('dashboard')
    op.drop_index('ix_task_error_row_number', table_name='task_error')
    op.drop_index('ix_task_error_processing_task_id', table_name='task_error')
    op.drop_index('ix_task_error_is_critical', table_name='task_error')
    op.drop_index('ix_task_error_error_type', table_name='task_error')
    op.drop_index('ix_task_error_error_code', table_name='task_error')
    op.drop_table('task_error')
    op.drop_index('ix_processing_log_stage', table_name='processing_log')
    op.drop_index('ix_processing_log_processing_task_id', table_name='processing_log')
    op.drop_index('ix_processing_log_level', table_name='processing_log')
    op.drop_index('ix_processing_log_created_at', table_name='processing_log')
    op.drop_table('processing_log')
    op.drop_index('ix_notification_user_id', table_name='notification')
    op.drop_index('ix_notification_type', table_name='notification')
    op.drop_index('ix_notification_report_id', table_name='notification')
    op.drop_index('ix_notification_project_id', table_name='notification')
    op.drop_index('ix_notification_processing_task_id', table_name='notification')
    op.drop_index('ix_notification_is_read', table_name='notification')
    op.drop_index('ix_notification_created_at', table_name='notification')
    op.drop_table('notification')
    op.drop_index('ix_normalized_dataset_report_id', table_name='normalized_dataset')
    op.drop_index('ix_normalized_dataset_created_at', table_name='normalized_dataset')
    op.drop_table('normalized_dataset')
    op.drop_index('ix_processing_task_status', table_name='processing_task')
    op.drop_index('ix_processing_task_report_upload_id', table_name='processing_task')
    op.drop_index('ix_processing_task_report_id', table_name='processing_task')
    op.drop_index('ix_processing_task_queued_at', table_name='processing_task')
    op.drop_index('ix_processing_task_ml_template_id', table_name='processing_task')
    op.drop_index('ix_processing_task_created_by', table_name='processing_task')
    op.drop_table('processing_task')
    op.drop_index('ix_report_upload_uploaded_by', table_name='report_upload')
    op.drop_index('ix_report_upload_report_type_id', table_name='report_upload')
    op.drop_index('ix_report_upload_report_id', table_name='report_upload')
    op.drop_index('ix_report_upload_project_id', table_name='report_upload')
    op.drop_index('ix_report_upload_is_latest', table_name='report_upload')
    op.drop_index('ix_report_upload_checksum_sha256', table_name='report_upload')
    op.drop_table('report_upload')
    op.drop_index('ix_report_status', table_name='report')
    op.drop_index('ix_report_report_type_id', table_name='report')
    op.drop_index('ix_report_project_id', table_name='report')
    op.drop_index('ix_report_ml_template_id', table_name='report')
    op.drop_index('ix_report_creator_id', table_name='report')
    op.drop_table('report')
    op.drop_index('ix_project_member_user_id', table_name='project_member')
    op.drop_index('ix_project_member_project_id', table_name='project_member')
    op.drop_table('project_member')
    op.drop_index('ix_audit_log_user_id', table_name='audit_log')
    op.drop_index('ix_audit_log_project_id', table_name='audit_log')
    op.drop_index('ix_audit_log_entity_type', table_name='audit_log')
    op.drop_index('ix_audit_log_entity_id', table_name='audit_log')
    op.drop_index('ix_audit_log_created_at', table_name='audit_log')
    op.drop_index('ix_audit_log_action', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_project_owner_id', table_name='project')
    op.drop_index('ix_project_is_archived', table_name='project')
    op.drop_table('project')
    op.drop_index('ix_ml_template_target_report_type_id', table_name='ml_template')
    op.drop_index('ix_ml_template_is_default', table_name='ml_template')
    op.drop_index('ix_ml_template_is_active', table_name='ml_template')
    op.drop_index('ix_ml_template_created_by', table_name='ml_template')
    op.drop_table('ml_template')
    op.drop_index('ix_user_role_id', table_name='user')
    op.drop_index('ix_user_is_blocked', table_name='user')
    op.drop_index('ix_user_is_active', table_name='user')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_index('ix_report_type_is_active', table_name='report_type')
    op.drop_table('report_type')
    # ### end Alembic commands ###